"""
Pydantic schemas for data validation
"""
from pydantic import BaseModel, Field, field_validator
from typing import List, Optional
from datetime import datetime


class PokemonBase(BaseModel):
    """Base schema for a Pokemon"""
    name: str = Field(..., min_length=1, max_length=100)
    types: str = Field(..., description="Types separated by / e.g: Fire/Flying")
    hp: int = Field(..., ge=1, le=300, description="Health Points")
    attack: int = Field(..., ge=1, le=300)
    defense: int = Field(..., ge=1, le=300)
    sp_attack: int = Field(..., ge=1, le=300, description="Special Attack")
    sp_defense: int = Field(..., ge=1, le=300, description="Special Defense")
    speed: int = Field(..., ge=1, le=300)

    @field_validator('types')
    @classmethod
    def validate_types(cls, v: str) -> str:
        """Validates types format: 'Fire/Water' or 'Electric'"""
        if not v or len(v.strip()) == 0:
            raise ValueError('Types cannot be empty')
        valid_types = {
            'Normal', 'Fire', 'Water', 'Electric', 'Grass', 'Ice',
            'Fighting', 'Poison', 'Ground', 'Flying', 'Psychic', 'Bug',
            'Rock', 'Ghost', 'Dragon', 'Dark', 'Steel', 'Fairy'
        }
        type_list = [t.strip() for t in v.split('/')]
        for t in type_list:
            if t not in valid_types:
                raise ValueError(f'Invalid type: {t}')
        return v

    @field_validator('name')
    @classmethod
    def validate_name(cls, v: str) -> str:
        """Validates Pokemon name"""
        return v.strip().capitalize()


class PokemonCreate(PokemonBase):
    """Schema for creating a Pokemon"""
    id: Optional[int] = Field(None, ge=1, description="Optional - auto-generated by database")


class PokemonResponse(PokemonBase):
    """Schema for Pokemon response"""
    id: int
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


class StatsResponse(BaseModel):
    """Schema for global statistics"""
    count: int
    avg_hp: float
    avg_attack: float
    avg_defense: float
    avg_sp_attack: float
    avg_sp_defense: float
    avg_speed: float
    max_hp: int = None
    max_attack: int = None
    min_hp: int = None
    min_attack: int = None


class SearchResponse(BaseModel):
    """Schema for search response"""
    query: str
    count: int
    data: List[PokemonResponse]
